import { Inter } from "next/font/google";
import "./globals.css";
import FooterComponent from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          justifyContent: "center",
          display: "flex",
          flexDirection: "column",
        }}
        className={inter.className}
      >
        <>
          {children}
          <FooterComponent />
        </>
      </body>
    </html>
  );
}
